### ISSUE TITLE
Linking issue: "thor-d.lib" cannot be opened

### ISSUE THREAD

**Issue by HossamBasion** [TheMaverickProgrammer/battlenetwork#11]
Hello there,

I am not sure if I did something wrong, but for some reason when I click play. I keep getting an error saying that "thor-d.lib" can't be opened.

**Comment by TheMaverickProgrammer** [comment]
The DLLs have to be in the same folder as the executable.

**Comment by HossamBasion** [comment]
I tried copying the dll files entirely in the same folder as the executable (The Debug one) and it still didn't work for some reason. I also noticed that thor-d.lib isn't in the repository when I searched for it. Am I supposed to download it from somewhere?

**Comment by TheMaverickProgrammer** [comment]
Hm I did away with Thor months ago. It might be lingering in the project
dependencies linker tab under project properties. Try taking it out.

**Comment by HossamBasion** [comment]
Hmm, How do I do that? I checked in Linker Input section, and I didn't find it included in the dependencies. But it's clearly referenced somewhere.

**Comment by TheMaverickProgrammer** [comment]
I take it you havent used visual studio before. that can be best found by
google searching and youtube videos. I cant write tutorials for vs at the
moment.

**Comment by TheMaverickProgrammer** [comment]
In the meantime, join the discord channel for the project. It's been growing members quick lately. I have a big release around the corner (see my /android branch) that builds on mobile. It has a lot more content and features as well. There's a #dev channel for developers there as well.

https://discord.gg/5NjGyY

**Comment by HossamBasion** [comment]
Thank you very much :)
