### ISSUE TITLE
Bugs from latest build

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [TheMaverickProgrammer/battlenetwork#7]
Other notable visual bugs are:
- flickering at intro
- chip text at bottom left hand gets jarbled for some reason
- cannon smoke jitters
- ~~for some reason when you have an aura and slide on the ice it looks like mega slides off tiles for a second even though code shows it stays on the same tile as expected~~

There are a few behavioral bugs I found: 
- moving objects can swap tiles. better lagging system can fix this.
- ~~bubbles try to put cubes in a bubble even though they don't the first time (expected behavior is to just pop)~~
- ~~If the player is removed temporarily from antidamage and the tile is destroyed, the player will spawn on top of a broken tile. Add reserve tile flag.~~
- Rare occasion: When all enemies are deleted, the reward never appeared preventing me from moving on
- ~~Bubbles are supposed to trap you as seen in older vids, will fix asap~~
- ~~Battling and then returning to select navi screen crashes~~
- ~~Add can drag rule so entities like cubes and gears do not pull~~

**Comment by ssbmars** [comment]
Buster/Chip buffering inaccuracy as it relates to movement-
Peashot/Chargeshot isn't properly buffered during movement. Instead it interrupts movement immediately, at any point in movement. Afterwards the remaining movement animation finishes. 
Proper behavior is that whatever is input first takes priority, be it movement or buster.  Pressing buster first has a small window to input a direction combination for NCP abilities. Pressing movement and buster on the same frame prioritizes movement, but a buster+direction combo for an NCP ability will still work from a same-frame input. Buster/chips can be buffered at any time during movement. Movement only has about a 5 frame input buffer. It won't follow through if it has to wait longer than that.

Charge hold bug-
If, while charging, B is let go of while moving, it's been observed that megaman can continue to charge as if B were still being held.

**Comment by TheMaverickProgrammer** [comment]
- You shouldnt be able to move while you shoot but I hadnt considered the condition shooting while moving. Easy fix.
- So movement is limited to 5 frames. Unsure what NCP means but I imagine its for input like DOWN + B = shield
- Did not know one was prioritized over the other. I'll look into implementing this behavior.
- Charge hold bug is an easy fix. Nice find.

**Comment by ssbmars** [comment]
Correction- normal buster shots don't interrupt movement, only chargeshot does. Buster+movement interactions will feel a lot better when the input buffer for both of them is properly implemented.

**Comment by TheMaverickProgrammer** [comment]
Ok so I understand: normal buster shots behave within the mechanics of 5-frame buffered input as described (with priorities and all) but **charged** shots are top priority and prevents movement completely.

**Comment by ssbmars** [comment]
I wasn't specific in my previous comment so I'll clarify just in case. The "correction" was for my observation of the bug in the build I'm testing on. I wasn't describing how the buster mechanic is intended to work.

**Comment by TheMaverickProgrammer** [comment]
Ya lost me. Whats the original mechanics? Dont worry about how mine is done i can change it.

**Comment by TheMaverickProgrammer** [comment]
Turns out the aura _was_ pushing the player off the screen. I use the new flag for sharing tile space on the aura and now they slide around as expected.

**Comment by TheMaverickProgrammer** [comment]
The remaining issues are added to my personal task list. Cannon smoke is just a positioning error. Flickering at intro will be resolved with a better state system. Moving objects with lag is a part of the next update.
