### ISSUE TITLE
So How About Adding a Basic Setup Guide.

### ISSUE THREAD

**Issue by Exraiel** [TheMaverickProgrammer/battlenetwork#8]
How do I run this theres no guide for basic users, its download Visual Studios IDE but without being told what to selection & where everything needs to be, how am I suppose to run this if I don't even know what files are what, add simple pictures, step 1 download battle network I think I did this not even sure I got the right files, step two download visual studios IDE I guess I click CC+Games What Else? step 3 what files in Battle network need to be placed into Visual Studio & Vice Versa if needed, its needed, step 4 tell me how to start Visual Studios & show me what file/buttons to click to run this emulation of Battle network, I don't see how anyone of you are suppose to gain followers when its basically unplayable to the average person unable to do all those complex steps.

**Comment by TheMaverickProgrammer** [comment]
The wiki getting started tells you how to compile and run on every platform

**Comment by Exraiel** [comment]
> The wiki getting started tells you how to compile and run on every platform

Well I saw that & it didn't show/teach me anything, I Downloaded Visual Studios & all the Github Code Files & have no ideal watch to do from there, I can't find the proper folders or files to do anything, I tried placing file in visual studio to build don't think thats what I'm even suppose to do, without detail instructions on wherre to place what & click what in the Visual Studio normal people can't run the game.

**Comment by TheMaverickProgrammer** [comment]
There's a visual studio project in the root directory. Double click on it and it has everything set up for you.

Everyone else has managed to get it compiling just fine. 

This isn't a project you can get involved with without knowing C++ development.

If you don't know how to code or don't want to code, just download and play the last public executable build [here](https://drive.google.com/file/d/1Ez21hk6OMa6mY9_mqBwTQCINuJMb-FMG/view?usp=sharing)

**Comment by Exraiel** [comment]
Thats Perfect Thx I see the Navi Sheets are what gives the animations? So how do I open Boom Sheet its listed as a jar program I have no native programs to launch it does Visual Studio do this too? Being able to test out y custom sprites this way is a dream come true,

**Comment by TheMaverickProgrammer** [comment]
Since I couldnt find anything online to do basic frame animations from spritesheets online I had to make my own alongside the engine. You can download BoomSheets [here](https://drive.google.com/open?id=14VfHECBqKm9f8mosB7hs1a4jEskzW1Z9)

Keep in mind it's ugly and may have bugs. Pretty much click and drag to make a frame. Click on a frame to edit properties on the right. Click update to save changes on the frame. Save/Save As to save the animation project to your computer. CTRL+Z is undo. Origin is the center of the tile in battle. Wherever that origin is is where your animation will show up in game. Press the Play button (at top) to preview the animation and see if it's lined up frame-by-frame.

**Comment by Exraiel** [comment]
I think I had to instal java first.

**Comment by Exraiel** [comment]
navi_megaman_atlas.png I'm just going to add my sprites here but when I did the sprite ingame had white around them what is the default ignore color, if none is this a layered png file needing photoshop.

**Comment by Exraiel** [comment]
![Megaman X Style](https://user-images.githubusercontent.com/50026246/56845412-6e7b6e00-6886-11e9-80ec-6d91782de78b.PNG)

**Comment by Exraiel** [comment]
![Uploading Megaman Z Style.PNG…]()
